VerticalAITWidget/Models/Widget.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace VerticalAITWidget.Models
{
    public class Widget
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [Required]
        [Column(TypeName = "DateTime2")]
        public DateTime CreatedDate { get; set; }

        public WidgetType WidgetType { get; set; }
        public int WidgetTypeId { get; set; }
    }
}

VerticalAITWidget/Models/WidgetType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VerticalAITWidget.Models
{
    public class WidgetType
    {

        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }
    }
}

VerticalAITWidget/Controllers/WidgetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VerticalAITWidget.Models;
using System.Data.Entity;
using VerticalAITWidget.ViewModels;

namespace VerticalAITWidget.Controllers
{
    public class WidgetsController : Controller
    {
        private ApplicationDbContext _context;

        public WidgetsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Widgets
        public ActionResult Index()
        {
            var widgets = _context.Widgets.Include(w => w.WidgetType).ToList();
            return View(widgets);
        }

        public ActionResult New()
        {
            var viewModel = new WidgetsTypeAndSubTypeViewModel
            {
                WidgetTypes = _context.WidgetTypes.ToList(),
                CreatedDate = DateTime.Now
            };

            return View("WidgetForm", viewModel);
        }

        [HttpPost]
        public ActionResult Save(Widget widget)
        {
            if(!ModelState.IsValid)
            {
                var viewModel = new WidgetsTypeAndSubTypeViewModel(widget)
                {
                    WidgetTypes = _context.WidgetTypes.ToList()
                };

                return View("WidgetForm", viewModel);
            }

            if(widget.Id == 0)
            {
                _context.Widgets.Add(widget);
            }

            else
            {
                var currentWidget = _context.Widgets.Single(w => w.Id == widget.Id);

                currentWidget.Name = widget.Name;
                currentWidget.CreatedDate = DateTime.Now;
                currentWidget.WidgetTypeId = widget.WidgetTypeId;
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Widget");
        }
    }
}

VerticalAITWidget/Views/Widgets/Index.cshtml
@model IEnumerable<VerticalAITWidget.Models.Widget>

@{
    ViewBag.Title = "Index";
}

<h2>Widgets</h2>

@if (!Model.Any())
{
<p>No Widgets To Display</p>
}
else
{
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Widget</th>
            <th>Creation Date</th>
            <th>Widget Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var widget in Model)
        {
        <tr>
            <td>@Html.ActionLink(widget.Name, "Edit", "Widget", new { id = widget.Id }, null)</td>
            <td>@widget.CreatedDate</td>
            <td>@widget.WidgetType.Name</td>
        </tr>
        }
    </tbody>
</table>
}

VerticalAITWidget/Views/Widgets/WidgetForm.cshtml
@model VerticalAITWidget.ViewModels.WidgetsTypeAndSubTypeViewModel
@{
    ViewBag.Title = "WidgetForm";
}

<h2>New Widget</h2>

@using(Html.BeginForm("Save", "Widgets"))
{

    <div class="form-group">
        @Html.LabelFor(w => w.Name)
        @Html.TextBoxFor(w => w.Name, new {@class="form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(w => w.WidgetTypeId)
        @Html.DropDownListFor(w => w.WidgetTypeId, new SelectList(Model.WidgetTypes, "Id", "Name"), new {@class="form-control"})
    </div>

    @Html.HiddenFor(w => w.Id)
    <button type="submit" class="btn btn-primary">Save</button>

}